Repository openshift/cluster-nfd-operator, pull requests merged in 2019-09, with the labels that each got.

#22 [Bug 1744167] nfd.package.yaml: match OCP channel name
  manifests/olm-catalog/nfd.package.yaml
Labels: lgtm, size/XS

#25 Bug 1753321: Update OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#24 Update art.yaml
  manifests/olm-catalog/art.yaml
Labels: size/XS

#21 During deployment and sed replacing the namespace two manifests were …
  Makefile
  manifests/0200_service_account.yaml
Labels: lgtm, size/XS

#23 Tolerate only worker nodes for custom taints
  assets/worker/0700_worker_daemonset.yaml
Labels: lgtm, size/XS

#27 Added CSV without WARNINGS, they are treated as Errors
  Makefile
  manifests/0600_operator.yaml
  manifests/olm-catalog/4.2/image-references
  manifests/olm-catalog/4.2/nfd.v4.2.0.clusterserviceversion.yaml
Labels: do-not-merge/hold, lgtm, size/M

#29 Csv config fixes
  assets/config/0110_namespace.yaml
  manifests/olm-catalog/4.2/nfd.v4.2.0.clusterserviceversion.yaml
  manifests/olm-catalog/nfd.package.yaml
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_resources.go
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_state.go
Labels: approved, lgtm, size/M

#28 Update Makefile
  Makefile
Labels: approved, lgtm, size/XS

#31 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS
