Repository openshift/cluster-nfd-operator, pull requests merged in 2020-02, with the labels that each got.

#60 Bug 1801367: Fix test-e2e make target
  Dockerfile.rhel7
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#63 add LICENSE apache 2.0
  LICENSE
Labels: approved, lgtm, size/L

#65 Fix Makefile variables declaration
  Makefile
Labels: approved, lgtm, size/S

#68 Set the correct namespace for SCC when installed in non default namespace
  Makefile
  pkg/controller/nodefeaturediscovery/nodefeaturediscovery_controls.go
Labels: approved, lgtm, size/XS

#66 [release-4.3] Bug 1805175: add GO111MODULE=on
  Makefile
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#73 [release-4.5] Bug 1808420: Add olm.skipRange and minKubeVersion keys to csv
  Dockerfile
  manifests/olm-catalog/4.5/image-references
  manifests/olm-catalog/4.5/nfd.crd.yaml
  manifests/olm-catalog/4.5/nfd.v4.4.0.clusterserviceversion.yaml
  manifests/olm-catalog/nfd.package.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#72 [release-4.4] Bug 1804889: Add olm.skipRange and minKubeVersion keys to csv
  manifests/olm-catalog/4.4/nfd.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
