Repository openshift/cluster-nfd-operator, pull requests merged in 2020-07, with the labels that each got.

#89 add kpouget to OWNERS file
  OWNERS
Labels: approved, lgtm

#95 CSV: remove duplicate `version` key
  manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#91 [release-4.5] Bug 1855312: Add support label for s390x & ppc64le
  manifests/olm-catalog/4.5/nfd.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#94 Bug 1813503: [release-4.5] Dockerfile not compatible with docker and…
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
