Repository openshift/cluster-nfd-operator, pull requests merged in 2021-05, with the labels that each got.

#161 Bug 1955714: fix art files
  manifests/4.8/manifests/nfd.v4.8.0.clustersrviceversion.yaml.yaml
  manifests/art.yaml
  manifests/nfd.package.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#162 Bug 1956354: Fix CSV file name
  manifests/4.8/manifests/nfd.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#164 Bug 1957846: Mount /usr inside the Pod
  build/assets/node-feature-discovery/05-nfd-daemonset.yml
  build/assets/worker/05_worker_ds.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#173 Bug 1961484: enable art replacement for kube-rbac-proxy image
  manifests/4.8/manifests/image-references
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
