Repository openshift/cluster-nfd-operator, pull requests merged in 2021-10, with the labels that each got.

#215 Bug 2009812: Remove namespace from controller-manager-alerts-monitor
  config/prometheus/monitor.yaml
  manifests/4.9/manifests/nfd-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-unspecified

#213 Move 4.10 to use stable channel
  .ci-operator.yaml
  Dockerfile
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/node-feature-discovery-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  manifests/4.10/bundle.Dockerfile
  manifests/4.10/manifests/controller-manager-alerts-monitor_monitoring.coreos.com_v1_prometheusrule.yaml
  manifests/4.10/manifests/controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/4.10/manifests/nfd-controller-manager-alerts-monitor_monitoring.coreos.com_v1_prometheusrule.yaml
  manifests/4.10/manifests/nfd-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/4.10/manifests/nfd-controller-manager-metrics-service_v1_service.yaml
  manifests/4.10/manifests/nfd-manager-config_v1_configmap.yaml
  manifests/4.10/manifests/nfd-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/4.10/manifests/nfd-operator_v1_serviceaccount.yaml
  manifests/4.10/manifests/nfd-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  manifests/4.10/manifests/nfd-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/4.10/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml
  manifests/4.10/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
  manifests/4.10/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  manifests/4.10/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/4.10/metadata/annotations.yaml
  manifests/4.10/tests/scorecard/config.yaml
  manifests/image-references
  manifests/nfd.package.yaml
  pkg/config/config.go
  version/version.go
Labels: approved, lgtm

#217 Fixing the CR name to apply nodes labeling in README.md
  README.md
Labels: approved, lgtm

#218 Bug 2011446: Fix CSV channel to stable
  Makefile
  manifests/4.9/bundle.Dockerfile
  manifests/4.9/metadata/annotations.yaml
  manifests/nfd.package.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#219 CSV: fix icon mediatype
  config/manifests/bases/node-feature-discovery-operator.clusterserviceversion.yaml
  manifests/4.10/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#220 CSV: fix kube-rbac-proxy image reference
  manifests/image-references
Labels: approved, lgtm
