Repository openshift/cluster-nfd-operator, pull requests merged in 2021-02, with the labels that each got.

#132 Bug 1923998: Remove readines probe from old operator sdk
  cmd/manager/main.go
  manifests/0600_operator.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#134 Bug 1923998: Remove readines probe from CSV
  manifests/olm-catalog/4.7/nfd.v4.7.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#116 added Recreate strategy instead of the default
  manifests/0600_operator.yaml
Labels: approved, lgtm

#135 Welcome to 4.8
  Dockerfile
  manifests/olm-catalog/4.8/image-references
  manifests/olm-catalog/4.8/nfd.crd.yaml
  manifests/olm-catalog/4.8/nfd.v4.8.0.clusterserviceversion.yaml
  manifests/olm-catalog/art.yaml
  manifests/olm-catalog/nfd.package.yaml
Labels: approved, lgtm

#131 [release-4.6] Bug 1924232: remove readiness probe from mounting tmp to enable upgrades from OLM
  cmd/manager/main.go
  manifests/0600_operator.yaml
  manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#137 Bug 1914869: replace latest for 4.7, so is easier to replace images by ART
  manifests/olm-catalog/4.7/image-references
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#139 OLM manifests: updated to match 4.8
  manifests/olm-catalog/4.8/image-references
  manifests/olm-catalog/4.8/nfd.v4.8.0.clusterserviceversion.yaml
Labels: approved, lgtm

#130 [release-4.5] Bug 1924236: Remove readines probe from old operator sdk
  cmd/manager/main.go
  manifests/0600_operator.yaml
  manifests/olm-catalog/4.5/nfd.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#127 [release-4.6] Bug 1916007: olm skip range is set to the wrong range
  manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
