Repository openshift/cluster-nfd-operator, pull requests merged in 2021-04, with the labels that each got.

#152 fix Error reconciling Dockerfile
  manifests/olm-catalog/4.8/image-references
  manifests/olm-catalog/4.8/nfd.crd.yaml
  manifests/olm-catalog/4.8/nfd.v4.8.0.clusterserviceversion.yaml
  manifests/olm-catalog/art.yaml
  manifests/olm-catalog/nfd.package.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#149 [release-4.6] Bug 1944244: Update nfd.v4.6.0.clusterserviceversion.yaml
  manifests/olm-catalog/4.6/nfd.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#153 Bug 1949102: Fix image build on disconnected envs
  Makefile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#154 Bug 1949276: Fix Operator RBAC policies
  Makefile
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#156 Bug 1952145: cluster-nfd-operator executable file not found in $PATH error
  Makefile
  config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
  manifests/0600_operator.yaml
  manifests/olm-catalog/4.8/nfd.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#159 Bug 1955248: fix kustomize for rbac roles
  Makefile
  config/manager/kustomization.yaml
  config/manifests/bases/node-feature-discovery-operator.clusterserviceversion.yaml
  config/rbac/kustomization.yaml
  manifests/4.8/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
