Repository openshift/cluster-nfd-operator, pull requests merged in 2021-07, with the labels that each got.

#163 Update courtneypacheco github user name on OWNERS file
  OWNERS
Labels: approved, lgtm

#183 Report NFD operator status in the nodefeaturediscoveries/nfd-instance…
  api/v1/nodefeaturediscovery_types.go
  api/v1/zz_generated.deepcopy.go
  controllers/nodefeaturediscovery_controller.go
  controllers/nodefeaturediscovery_controls.go
  controllers/nodefeaturediscovery_status.go
  go.sum
Labels: approved, lgtm, tide/merge-method-squash

#185 Bug 1985465: Fix error messages that occur after degraded and progressing resources
  controllers/nodefeaturediscovery_controller.go
  controllers/nodefeaturediscovery_status.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#186 Add metrics and alerts to NFD Operator
  Makefile
  README.md
  api/v1/nodefeaturediscovery_types.go
  build/assets/node-feature-discovery/00-nfd-serviceaccount.yml
  build/assets/node-feature-discovery/02-nfd-clusterrolebinding.yml
  build/assets/node-feature-discovery/03-nfd-securitycontextconstraint.yml
  build/assets/node-feature-discovery/04-nfd-configmap.yml
  build/assets/node-feature-discovery/05-nfd-daemonset.yml
  config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/manager.yaml
  config/manifests/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role_binding.yaml
  controllers/nodefeaturediscovery_controller.go
  controllers/nodefeaturediscovery_controls.go
  controllers/nodefeaturediscovery_resources.go
  controllers/nodefeaturediscovery_state.go
  controllers/nodefeaturediscovery_status.go
  go.mod
  go.sum
  main.go
  manifests/4.9/bundle.Dockerfile
  manifests/4.9/manifests/controller-manager-alerts-monitor_monitoring.coreos.com_v1_prometheusrule.yaml
  manifests/4.9/manifests/controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/4.9/manifests/nfd-controller-manager-alerts-monitor_monitoring.coreos.com_v1_prometheusrule.yaml
  manifests/4.9/manifests/nfd-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/4.9/manifests/nfd-controller-manager-metrics-service_v1_service.yaml
  manifests/4.9/manifests/nfd-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
  manifests/4.9/manifests/nfd-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  manifests/4.9/manifests/nfd-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/4.9/manifests/nfd-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/4.9/manifests/nfd-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  manifests/4.9/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml
  manifests/4.9/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
  manifests/4.9/metadata/annotations.yaml
  nfd.package.yaml
  pkg/config/config.go
  pkg/controller/nodefeaturediscovery/components/components.go
  pkg/metrics/metrics.go
  pkq/config/config.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/model/fnv.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/modules.txt
  version/version.go
Labels: approved, lgtm

#187 Bug 1986305: drop operand images as required field on CRD
  Makefile
  api/v1/nodefeaturediscovery_types.go
  config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
  config/manifests/bases/node-feature-discovery-operator.clusterserviceversion.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#188 art.yaml: match CSV filename
  manifests/art.yaml
Labels: approved, lgtm

#175 Bug 1967314: fix logo not present when using OperatorHub
  config/manifests/bases/node-feature-discovery-operator.clusterserviceversion.yaml
  manifests/4.9/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#190 Update CSV fields
  api/v1/nodefeaturediscovery_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
  config/manifests/bases/node-feature-discovery-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  manifests/4.9/manifests/node-feature-discovery-operator.clusterserviceversion.yaml
Labels: approved, lgtm
