Repository openshift/cluster-nfd-operator, pull requests merged in 2021-06, with the labels that each got.

#174 Bug 1966725: enhance the alm-example
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
  manifests/4.8/manifests/nfd.v4.8.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#170 Adding documentation for each function and var related to 'Resources'
  controllers/nodefeaturediscovery_resources.go
Labels: approved, lgtm

#171 Adding documentation for controller 'state' functions and vars
  controllers/nodefeaturediscovery_state.go
Labels: approved, lgtm

#155 Update Owners
  OWNERS
Labels: approved, lgtm

#179 release-4.9-olm-manifests
  Dockerfile
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/node-feature-discovery-operator.clusterserviceversion.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
  manifests/4.9/bundle.Dockerfile
  manifests/4.9/manifests/image-references
  manifests/4.9/manifests/nfd-controller-manager-metrics-service_v1_service.yaml
  manifests/4.9/manifests/nfd-leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
  manifests/4.9/manifests/nfd-leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/4.9/manifests/nfd-manager-config_v1_configmap.yaml
  manifests/4.9/manifests/nfd-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/4.9/manifests/nfd-operator_v1_serviceaccount.yaml
  manifests/4.9/manifests/nfd-proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/4.9/manifests/nfd-proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  manifests/4.9/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml
  manifests/4.9/manifests/nfd.v4.9.0.clusterserviceversion.yaml
  manifests/4.9/metadata/annotations.yaml
  manifests/nfd.package.yaml
  pkq/config/config.go
Labels: approved, lgtm

#180 Add support label for arm64
  manifests/4.9/manifests/nfd.v4.9.0.clusterserviceversion.yaml
Labels: approved, lgtm

#172 Adding documentation for NFD controls
  controllers/nodefeaturediscovery_controls.go
Labels: approved, lgtm

#167 Adding documentation for the health check flag in 'main.go'
  main.go
Labels: approved, lgtm, ¯\_(ツ)_/¯

#168 Adding documentation for the controller reconciliation funcs and struct
  controllers/nodefeaturediscovery_controller.go
Labels: approved, lgtm

#165 Adding documentation for the leader election flag in 'main.go'
  main.go
Labels: approved, lgtm

#166 Updating documentation in 'main.go' for 'metricsAddr'
  main.go
Labels: approved, lgtm

#169 Adding documentation for NFD related structs (types)
  controllers/nodefeaturediscovery_resources.go
  controllers/nodefeaturediscovery_state.go
Labels: approved, lgtm

#160 remove Dockerfile no longer needed
  Dockerfile.rhel7
Labels: approved, lgtm

#177 Update and enhance README
  README.md
Labels: approved, lgtm
