Repository openshift/cluster-nfd-operator, pull requests merged in 2022-02, with the labels that each got.

#240 bug 2019945: Move references to 4.11
  .ci-operator.yaml
  .gitignore
  Dockerfile
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/nfd.clusterserviceversion.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
  controllers/nodefeaturediscovery_finalizers.go
  manifests/4.11/bundle.Dockerfile
  manifests/4.11/manifests/controller-manager-alerts-monitor_monitoring.coreos.com_v1_prometheusrule.yaml
  manifests/4.11/manifests/controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/4.11/manifests/nfd-controller-manager-alerts-monitor_monitoring.coreos.com_v1_prometheusrule.yaml
  manifests/4.11/manifests/nfd-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/4.11/manifests/nfd-controller-manager-metrics-service_v1_service.yaml
  manifests/4.11/manifests/nfd-manager-config_v1_configmap.yaml
  manifests/4.11/manifests/nfd-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/4.11/manifests/nfd-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  manifests/4.11/manifests/nfd-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/4.11/manifests/nfd.clusterserviceversion.yaml
  manifests/4.11/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml
  manifests/4.11/manifests/nfd.openshift.io_nodefeaturerules.yaml
  manifests/4.11/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  manifests/4.11/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/4.11/manifests/topology.node.k8s.io_noderesourcetopologies.yaml
  manifests/4.11/metadata/annotations.yaml
  manifests/4.11/tests/scorecard/config.yaml
  manifests/image-references
  manifests/nfd.package.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#239 Bug 2048617: Add finalizer status report
  PROJECT
  api/v1/nodefeaturediscovery_types.go
  config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
  config/default/kustomization.yaml
  config/manifests/bases/nfd.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  controllers/nodefeaturediscovery_controller.go
  controllers/nodefeaturediscovery_controls.go
  controllers/nodefeaturediscovery_finalizers.go
  controllers/nodefeaturediscovery_state.go
  manifests/4.10/bundle.Dockerfile
  manifests/4.10/manifests/nfd.clusterserviceversion.yaml
  manifests/4.10/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml
  manifests/4.10/metadata/annotations.yaml
  manifests/art.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#238 Bug 2051988: Drop namespace from CRD
  .gitignore
  PROJECT
  api/v1/nodefeaturediscovery_types.go
  config/certmanager/certificate.yaml
  config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/nfd.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
  controllers/nodefeaturediscovery_controller.go
  controllers/nodefeaturediscovery_controls.go
  controllers/nodefeaturediscovery_finalizers.go
  controllers/nodefeaturediscovery_resources.go
  controllers/nodefeaturediscovery_state.go
  controllers/nodefeaturediscovery_status.go
  main.go
  manifests/4.9/manifests/nfd-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/4.9/manifests/nfd.clusterserviceversion.yaml
  manifests/4.9/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml
  manifests/art.yaml
  pkg/config/config.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#241 Bug 2055049: Do not set explicitly image pull policy to Always
  config/manager/manager.yaml
  config/manifests/bases/nfd.clusterserviceversion.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
  manifests/4.11/manifests/nfd.clusterserviceversion.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#242 [release-4.10] Bug 2055244: Do not set explicitly image pull policy to Always
  config/manager/manager.yaml
  config/manifests/bases/nfd.clusterserviceversion.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
  manifests/4.10/manifests/nfd.clusterserviceversion.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#243 [release-4.9] Bug 2055318: Do not set explicitly image pull policy to Always
  config/manager/manager.yaml
  config/manifests/bases/nfd.clusterserviceversion.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
  manifests/4.9/manifests/nfd.clusterserviceversion.yaml
  manifests/4.9/metadata/annotations.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#244 Bug 2055436: Update NodeFeatureRules api group
  build/assets/master/0200_clusterrole.yaml
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
