Repository openshift/cluster-nfd-operator, pull requests merged in 2024-03, with the labels that each got.

#357 Setting infra labels in the clusterserviceversion
  config/manifests/bases/nfd.clusterserviceversion.yaml
  manifests/stable/manifests/nfd.clusterserviceversion.yaml
Labels: approved, lgtm

#360 OCPBUGS-30735: [release4-14] Setting infra labels in the clusterserviceversion
  config/manifests/bases/nfd.clusterserviceversion.yaml
  manifests/stable/manifests/nfd.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#361 replace old version numbers with the correct 4.16
  config/manager/manager.yaml
  config/manifests/bases/nfd.clusterserviceversion.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
  manifests/image-references
  manifests/nfd.package.yaml
  manifests/stable/manifests/nfd.clusterserviceversion.yaml
  pkg/config/config.go
Labels: approved, lgtm

#362 backport version number updates to 4.16 branch
  config/manager/manager.yaml
  config/manifests/bases/nfd.clusterserviceversion.yaml
  config/samples/nfd.openshift.io_v1_nodefeaturediscovery.yaml
  manifests/image-references
  manifests/nfd.package.yaml
  manifests/stable/manifests/nfd.clusterserviceversion.yaml
  pkg/config/config.go
Labels: approved

#363 OCPBUGS-30858: Setting infra labels in the clusterserviceversion
  config/manifests/bases/nfd.clusterserviceversion.yaml
  manifests/stable/manifests/nfd.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#364 OCPBUGS-30863: Setting infra labels in the clusterserviceversion
  config/manifests/bases/nfd.clusterserviceversion.yaml
  manifests/4.12/manifests/nfd.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#365 upstream backport adjustment
  Dockerfile.cluster-nfd-operator-build
  Makefile
  api/v1/nodefeaturerules_types.go
  api/v1/zz_generated.deepcopy.go
  build/assets/worker/02_worker_role.yaml
  build/assets/worker/05_worker_ds.yaml
  config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
  config/crd/bases/nfd.openshift.io_nodefeaturerules.yaml
  config/crd/bases/nfd.openshift.io_nodefeatures.yaml
  config/crd/bases/nfd.openshift.io_v1_nodefeaturediscoveries.yaml
  config/crd/bases/nfd.openshift.io_v1alpha1_nodefeaturerules.yaml
  config/rbac/role.yaml
  manifests/stable/manifests/nfd.clusterserviceversion.yaml
  manifests/stable/manifests/nfd.openshift.io_nodefeaturediscoveries.yaml
  manifests/stable/manifests/nfd.openshift.io_nodefeaturerules.yaml
Labels: approved, lgtm
