Repository openshift/cluster-nfd-operator, pull requests merged in 2024-05, with the labels that each got.

#369 fixing bundle creation
  config/crd/kustomization.yaml
Labels: approved, lgtm

#367 OCPBUGS-32940: backport the extendedResources etc fields into the rules CRD
  manifests/stable/manifests/nfd.openshift.io_nodefeaturerules.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#368 OCPBUGS-31488: backport the extendedResources and taint fields into the rules CRD
  manifests/stable/manifests/nfd.openshift.io_nodefeaturerules.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#371 OCPBUGS-33287: set the image to match what art will replace (in image-references)
  manifests/stable/manifests/nfd.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#375 OCPBUGS-31488: add node-feature-rules crd changes from #348 to config
  config/crd/bases/nfd.openshift.io_v1alpha1_nodefeaturerules.yaml
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
