Repository openshift/cluster-nfd-operator, pull requests merged in 2024-01, with the labels that each got.

#341 Add NodeFeature CRD to the deployment/bundle and adding new fields
  Dockerfile.cluster-nfd-operator-build
  Makefile
  config/crd/bases/nfd.openshift.io_nodefeaturediscoveries.yaml
  config/crd/bases/nfd.openshift.io_v1alpha1_nodefeaturerules.yaml
  config/crd/bases/nfd.openshift.io_v1alpha1_nodefeatures.yaml
  config/crd/kustomization.yaml
  config/manager/kustomization.yaml
Labels: approved, lgtm

#346 changing CSV to 4.16
  Dockerfile
Labels: approved, lgtm

#343 OCPBUGS-28390: fixing CSV version of the Dockerfile
  Dockerfile
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#342 NO-ISSUE: Fix trailing space
  README.md
Labels: approved, lgtm, jira/valid-reference
