Repository openshift/cluster-nfd-operator, pull requests merged in 2025-06, with the labels that each got.

#436 Removing downstream NodeFeatureGroup from the bundle
  manifests/stable/manifests/nfd.openshift.io_nodefeaturegroups.yaml
Labels: approved, lgtm

#438 ART-13079: append .0 to go.mod version
  go.mod
Labels: jira/valid-reference

#440 Updating cluster-nfd-operator image to be consistent with ART for 4.20
  .ci-operator.yaml
  Dockerfile
  Dockerfile.cluster-nfd-operator-build
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/nfd.clusterserviceversion.yaml
  manifests/image-references
  manifests/nfd.package.yaml
  manifests/stable/manifests/nfd.clusterserviceversion.yaml
Labels: approved, lgtm

#441 [ART-13123] append .0 to go.mod version
  go.mod
Labels: approved, lgtm, backport-risk-assessed

#446 Fixing official bundle generation
  manifests/stable/manifests/nfd-master_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/stable/manifests/nfd-worker_rbac.authorization.k8s.io_v1_role.yaml
Labels: approved, lgtm
